### ISSUE TITLE
Scala Websocket

### ISSUE THREAD

**Issue by Hjalmar3** [ticofab/simple-play-websocket-server#1]
@ticofab I have a question / offer with respect to scala and websocket. Could you please contact me. My email address is hjalmar 'dot' peters 'at' gmx.de

**Comment by ticofab** [comment]
Hey HJalmar3,
Thanks for making contact. It sounds like you're in Germany? Must be quite
hot there these days.
Cheers
Fabio

On 3 July 2015 at 17:38, Hjalmar3 notifications@github.com wrote:

> @ticofab https://github.com/ticofab I have a question / offer with
> respect to scala and websocket. Could you please contact me. My email
> address is hjalmar 'dot' peters 'at' gmx.de
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ticofab/simple-play-websocket-server/issues/1.

## 

http://famsterdamlife.com

**Comment by Hjalmar3** [comment]
Hi Fabio,

indeed, it is! Here in Karlsruhe, we’re approaching 40°C!

I stumbled over your simple-play-websocket-server/client and the corresponding presentation at SlideShare. I wonder, whether you can assist me with the problem described below. If so, how much would it cost?

Here's my problem: I have two computers A and B on distinct locations with a Scala program running on each. I want these two Scala programs to communicate. From what I read in the web, I think the best way would be a websocket connection. Unfortunately I wasn't able to find a simple-enough tutorial on how to establish such a connection. Could you help me creating a simple working example (i.e., two Scala programs, one running on A and the other on B, that are able to exchange messages via websocket)?  

All the best,

Hjalmar

PS.: I use IntelliJ IDEA 14 as IDE, and Scala 2.11.7
